services:
  # Development services
  postgres:
    image: ghcr.io/serverpod/postgres:16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: routineflow
      POSTGRES_PASSWORD: "FZvQwxVPKrwLyda4pE-XowoMf946h1_2"
    volumes:
      - routineflow_data:/var/lib/postgresql/data


  # Test services
  postgres_test:
    image: ghcr.io/serverpod/postgres:16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: routineflow_test
      POSTGRES_PASSWORD: "TJt_Wi4FZPmo6CkthYvBbUGn2hSxJA5_"
    volumes:
      - routineflow_test_data:/var/lib/postgresql/data


volumes:
  routineflow_data:
  routineflow_test_data:
