development:
  database: 'FZvQwxVPKrwLyda4pE-XowoMf946h1_2'
  serviceSecret: 'oZqO6YkzglSCEAIw3ozKmPz9cd6ip2K1'
  emailSecretHashPepper: 'Ykm0hMqsj8mFWyENTFDpM3RjbAMZDexv'
  jwtHmacSha512PrivateKey: 'QRyyRhMptaWfLZmV_1cNQ3e5gWhy3yoF'
  jwtRefreshTokenHashPepper: '9e8EXufMkLzywDIv6F9OwDFDCccftGsb'

test:
  database: 'TJt_Wi4FZPmo6CkthYvBbUGn2hSxJA5_'
  emailSecretHashPepper: 'w6rV3ue86R8XOHSK5_q7ubbHaaoBx-FM'
  jwtHmacSha512PrivateKey: 'LvflX2MnL4QOpLRJoyxu_aRxAgzM0rDk'
  jwtRefreshTokenHashPepper: 'rUi-bfu4dkbpWTsMmALELHDEvMMM_Ene'

staging:
  database: 'YqHuaTvcANycYUBZz-CTzwyu9yymbw8l'
  serviceSecret: 'LX4Kv8c3hzGTYxXpOAzfNUjX3SAK0ZrL'
  emailSecretHashPepper: 'LpoHdVJXzmnc0djS0szoPmiehkjd_yg-'
  jwtHmacSha512PrivateKey: 'DO8twx5-5UQQKNjs0mhD6qslWNzzIih1'
  jwtRefreshTokenHashPepper: 'vZrAWCPWpJ67YvaVs4DCjA9gdYhVKZuO'

production:
  database: 'LqJoJhKQnS0vs8vIiMe4K52gE4W7ysNc'
  serviceSecret: 'MN4HuLhlp_Y3kCEuRTGVClRirB41eDdP'
  emailSecretHashPepper: 'rdFVe8OMx3PBKdRtcx3z3r22fgF5xAcT'
  jwtHmacSha512PrivateKey: 'iztyedgRRucAmoE_UreJiZXSGQiEQl_1'
  jwtRefreshTokenHashPepper: 'lSm-QpIkdjwAhw2pNNQAQIRQpgwktl-9'
