# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
# shared:
#   # Example custom secret. Uncomment and rename to store a value shared
#   # across all run modes. Access via `pod.getPassword('mySharedPassword')`.
#   mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: 'FZvQwxVPKrwLyda4pE-XowoMf946h1_2'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'oZqO6YkzglSCEAIw3ozKmPz9cd6ip2K1'

  emailSecretHashPepper: 'Ykm0hMqsj8mFWyENTFDpM3RjbAMZDexv'
  jwtHmacSha512PrivateKey: 'QRyyRhMptaWfLZmV_1cNQ3e5gWhy3yoF'
  jwtRefreshTokenHashPepper: '9e8EXufMkLzywDIv6F9OwDFDCccftGsb'
  # Random value to be used as a pepper for the server-side sessions hash.
  # Only required if using `ServerSideSessionsConfigFromPasswords()` as token
  # manager on `tokenManagerBuilders` in lib/server.dart. Safe to remove from
  # the run modes that won't use it.
  # serverSideSessionKeyHashPepper: 'K0bTSsUAjqJ3bo6g6YLty3JNmBzltFce'

test:
  database: 'TJt_Wi4FZPmo6CkthYvBbUGn2hSxJA5_'

  emailSecretHashPepper: 'w6rV3ue86R8XOHSK5_q7ubbHaaoBx-FM'
  jwtHmacSha512PrivateKey: 'LvflX2MnL4QOpLRJoyxu_aRxAgzM0rDk'
  jwtRefreshTokenHashPepper: 'rUi-bfu4dkbpWTsMmALELHDEvMMM_Ene'
  # serverSideSessionKeyHashPepper: 'fZ9cpqb_pBt16tDJ9Ai3uHge1LtiVvA-'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: 'YqHuaTvcANycYUBZz-CTzwyu9yymbw8l'
  serviceSecret: 'LX4Kv8c3hzGTYxXpOAzfNUjX3SAK0ZrL'

  emailSecretHashPepper: 'LpoHdVJXzmnc0djS0szoPmiehkjd_yg-'
  jwtHmacSha512PrivateKey: 'DO8twx5-5UQQKNjs0mhD6qslWNzzIih1'
  jwtRefreshTokenHashPepper: 'vZrAWCPWpJ67YvaVs4DCjA9gdYhVKZuO'
  # serverSideSessionKeyHashPepper: 'HjrMnUY16oNt5DIwh5BUKkL_wlsxZbgu'

# Passwords used in production mode.
production:
  database: 'LD9q80pEmoTeoVsC2aQ9owzeODEsa0cr'
  serviceSecret: 'MN4HuLhlp_Y3kCEuRTGVClRirB41eDdP'

  emailSecretHashPepper: 'rdFVe8OMx3PBKdRtcx3z3r22fgF5xAcT'
  jwtHmacSha512PrivateKey: 'iztyedgRRucAmoE_UreJiZXSGQiEQl_1'
  jwtRefreshTokenHashPepper: 'lSm-QpIkdjwAhw2pNNQAQIRQpgwktl-9'
  # serverSideSessionKeyHashPepper: 'rmJB-JRugLCadII57DxGHBUqlR7KJznb'
