apiServer:
  port: 8080
  publicHost: routineflow-backend.onrender.com
  publicPort: 443
  publicScheme: https

insightsServer:
  port: 8081
  publicHost: routineflow-backend.onrender.com
  publicPort: 443
  publicScheme: https

webServer:
  port: 8082
  publicHost: routineflow-backend.onrender.com
  publicPort: 443
  publicScheme: https

database:
  host: ${SERVERPOD_DATABASE_HOST}
  port: ${SERVERPOD_DATABASE_PORT}
  name: ${SERVERPOD_DATABASE_NAME}
  user: ${SERVERPOD_DATABASE_USER}
  password: ${SERVERPOD_DATABASE_PASSWORD}

applyMigrations: true

redis:
  enabled: false
