










apiServer:
  port: 8080
  publicHost: api-staging.examplepod.com
  publicPort: 443
  publicScheme: https


insightsServer:
  port: 8081
  publicHost: insights-staging.examplepod.com
  publicPort: 443
  publicScheme: https


webServer:
  port: 8082
  publicHost: app-staging.examplepod.com
  publicPort: 443
  publicScheme: https





database:
  host: database.private-staging.examplepod.com
  port: 5432
  name: serverpod
  user: postgres
  requireSsl: true




maxRequestSize: 524288

sessionLogs:

























